// lib/data.js — Complete data for all detail pages

// ─── BLOG POSTS (full content) ────────────────────────────────────────────────
export const BLOG_DATA = {
  "naivasha-itinerary": {
    slug: "naivasha-itinerary",
    title: "The Ultimate 3-Day Naivasha Itinerary",
    category: "Itineraries",
    date: "March 1, 2026",
    readTime: "8 min read",
    excerpt: "Everything you need to know for the perfect lake escape",
    img: "https://images.unsplash.com/photo-1540202403-b7abd6747a18?w=1400&q=85",
    author: { name: "Rooted Kenya", avatar: "https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=100&q=80" },
    tags: ["Naivasha","Itinerary","Weekend","Lake"],
    body: [
      { type:"intro", text:"Naivasha is 90km from Nairobi — close enough for a Friday evening departure, far enough to feel genuinely away. This 3-day itinerary is built for real life: it accounts for traffic, real costs, and the kind of experience that makes you want to go back." },
      { type:"h2", text:"Day 1: Drive Down & First Night" },
      { type:"p", text:"Leave Nairobi no later than 4pm on Friday. The Nakuru highway is fast once you clear Westlands. You'll hit the Rift Valley escarpment viewpoint at dusk — pull over. It's one of Kenya's great views." },
      { type:"p", text:"Check in, shower, then head to Camp Carnelley's or your hotel's outdoor area for dinner. Most lakeside properties do bonfire evenings on Fridays. Bring a jacket — Naivasha nights are cold year-round." },
      { type:"h2", text:"Day 2: Hell's Gate & The Lake" },
      { type:"p", text:"Hell's Gate National Park opens at 6am. Get there by 7:30am before the tour groups arrive. Rent bikes at the gate (KES 600/day) and cycle through the gorge — the cliffs and hot springs are genuinely dramatic." },
      { type:"p", text:"Afternoon: book a boat to Crescent Island. You walk among giraffes, zebras, and wildebeest completely unfenced. It's one of those experiences that feels unreal. Costs around KES 2,500pp." },
      { type:"p", text:"Sundowner back at the hotel — most arrange a lake boat ride at sunset. Hippos grunt, fish eagles call. Have the gin and tonic." },
      { type:"h2", text:"Day 3: Morning Walk & Head Back" },
      { type:"p", text:"Wake up early for a nature walk. If you're staying at Enashipai or Great Rift Valley Lodge, the grounds alone are worth an early wander. Check out by 11am and stop at the Naivasha flower market on the way out — fresh roses for KES 200 a bunch." },
      { type:"tip", text:"Book Hell's Gate bike hire in advance during peak season (December, Easter, August). The gorge can get busy but the cliffs are always worth it." },
    ],
    relatedSlugs: ["first-safari","48-hours-diani","kenya-eta-guide"],
  },
  "nairobi-brunch": {
    slug: "nairobi-brunch",
    title: "Best Brunch Spots in Nairobi",
    category: "Food",
    date: "February 28, 2026",
    readTime: "6 min read",
    excerpt: "Where to find the perfect weekend brunch experience",
    img: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1400&q=85",
    author: { name: "Rooted Kenya", avatar: "https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=100&q=80" },
    tags: ["Nairobi","Brunch","Food","Restaurants"],
    body: [
      { type:"intro", text:"Nairobi's brunch scene has grown remarkably in the past three years. From garden restaurants in Karen to rooftop terraces in Westlands, there are now genuinely excellent options for every budget and vibe." },
      { type:"h2", text:"Karen & Ngong Road" },
      { type:"p", text:"Talisman Restaurant remains the gold standard for a Karen brunch. The garden setting, the quality of the food, and the unhurried pace make it worth the slightly higher price point. Book 3–5 days ahead for weekends." },
      { type:"p", text:"About Thyme on Ngong Road is the more relaxed alternative — excellent coffee, healthy bowls, and a quiet garden. Less Instagrammed, consistently good." },
      { type:"h2", text:"Westlands & Parklands" },
      { type:"p", text:"Brew Bistro at the Top has the best rooftop views of any brunch spot in the city. The food quality has improved significantly this year. Sunday is the best day — they run the full brunch menu." },
      { type:"p", text:"Cultiva is the current crowd favourite — bottomless mimosas, a stunning garden, and eggs done properly. The wait for walk-ins can be 45 minutes on a Sunday. Always book." },
      { type:"h2", text:"Budget-Friendly Options" },
      { type:"p", text:"The Artcaffe outlets across the city are reliable, consistent, and well-priced. The one in the Village Market is the most pleasant setting. Expect KES 800–1,400 for a full breakfast." },
      { type:"tip", text:"Most top brunch spots stop taking reservations 24hrs before on weekends — WhatsApp them directly for a better chance of a table." },
    ],
    relatedSlugs: ["nairobi-nyama-choma","naivasha-itinerary","48-hours-diani"],
  },
  "first-safari": {
    slug: "first-safari",
    title: "Planning Your First Kenyan Safari",
    category: "Safari",
    date: "February 25, 2026",
    readTime: "10 min read",
    excerpt: "A complete guide to safari planning for first-timers",
    img: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1400&q=85",
    author: { name: "Rooted Kenya", avatar: "https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=100&q=80" },
    tags: ["Safari","Maasai Mara","Amboseli","Planning"],
    body: [
      { type:"intro", text:"A first safari is one of those experiences that genuinely changes how you see the world. Kenya is the best place to do it — the variety of parks, the quality of guides, and the infrastructure make it accessible without being a manufactured experience." },
      { type:"h2", text:"Which Park Should You Choose?" },
      { type:"p", text:"For most first-timers, the Maasai Mara is the answer. It has the highest density of big cats in Africa, and during July–October you can witness the Great Migration — one of the greatest wildlife spectacles on earth." },
      { type:"p", text:"Amboseli is better for elephant photography and is slightly more affordable. The views of Kilimanjaro behind a herd of elephants are iconic. Go between January–February or June–October." },
      { type:"h2", text:"Tour vs Self-Drive" },
      { type:"p", text:"For a first safari, go with a tour operator. A good guide is the difference between spotting a leopard in a tree and driving past it three times. Budget KES 6,000–12,000/day for a quality private guide." },
      { type:"p", text:"Self-drive is viable if you're experienced with off-road driving and navigation in open plains. Bring a backup battery, offline maps, and don't push your luck after 6pm." },
      { type:"h2", text:"What to Pack" },
      { type:"p", text:"Neutral colours only (khaki, olive, grey). Avoid blue and black — they attract tsetse flies. Mornings in the vehicle are cold even in August — bring layers. A good camera with a 200mm+ zoom lens will change your photos." },
      { type:"tip", text:"The golden rule: listen to your guide. They know where the animals are. Patience is the biggest factor between an average safari and an exceptional one." },
    ],
    relatedSlugs: ["naivasha-itinerary","48-hours-diani","kenya-eta-guide"],
  },
  "48-hours-diani": {
    slug: "48-hours-diani",
    title: "48 Hours in Diani Beach",
    category: "Destinations",
    date: "February 20, 2026",
    readTime: "5 min read",
    excerpt: "The perfect quick escape to Kenya's finest white-sand coast",
    img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=85",
    author: { name: "Rooted Kenya", avatar: "https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=100&q=80" },
    tags: ["Diani","Beach","Weekend","Coast"],
    body: [
      { type:"intro", text:"Forty-eight hours is enough time to properly experience Diani if you're deliberate about it. Fly down (1 hour, from KES 8,000 one-way), leave Friday evening, return Sunday afternoon." },
      { type:"h2", text:"Friday Evening" },
      { type:"p", text:"Land at Ukunda airstrip — it's a 15-minute tuk-tuk to most beach hotels. Check in, change, and walk down to 40 Thieves Beach Bar for your first Tusker with your feet in the sand. This is mandatory." },
      { type:"p", text:"Dinner at Ali Barbour's Cave Restaurant. A coral cave, candlelight, fresh seafood. Reserve before you fly — it fills completely on weekends." },
      { type:"h2", text:"Saturday: The Full Diani Day" },
      { type:"p", text:"7am: Beach walk south toward Galu Beach before the sun is fully up. The northern end gets more crowded; Galu stays quiet and locals come here." },
      { type:"p", text:"10am: Kisite-Mpunguti Marine Park snorkelling trip. A dhow takes you out for a half-day — dolphins almost guaranteed, turtles likely, coral in good condition. Budget KES 3,500pp." },
      { type:"p", text:"Afternoon: Colobus monkey sanctuary. Free entry. 30-minute guided walk. The black-and-white colobus monkeys are striking and surprisingly approachable." },
      { type:"h2", text:"Sunday: Last Morning" },
      { type:"p", text:"Sunrise swim. Late breakfast at your hotel. One more walk. Then pack and head to the airstrip. Two days of salt air, good food, and actual relaxation." },
      { type:"tip", text:"The SGR to Mombasa (from Nairobi, 4.5hrs, KES 1,200) is great value if you're not in a rush. Matatu from Mombasa to Diani takes about 45 minutes." },
    ],
    relatedSlugs: ["naivasha-itinerary","first-safari","kenya-eta-guide"],
  },
  "kenya-eta-guide": {
    slug: "kenya-eta-guide",
    title: "Kenya eTA: Everything You Need to Know",
    category: "Travel Tips",
    date: "February 15, 2026",
    readTime: "7 min read",
    excerpt: "A step-by-step guide to getting your Kenya electronic visa",
    img: "https://images.unsplash.com/photo-1488085061387-422e29b40080?w=1400&q=85",
    author: { name: "Rooted Kenya", avatar: "https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=100&q=80" },
    tags: ["Travel Tips","eTA","Visa","First Time"],
    body: [
      { type:"intro", text:"Kenya replaced its traditional visa system with an Electronic Travel Authorisation (eTA) in 2024. The process is mostly straightforward but there are a few pitfalls worth knowing before you apply." },
      { type:"h2", text:"Who Needs an eTA?" },
      { type:"p", text:"Most visitors to Kenya now require an eTA regardless of nationality. East African Community citizens (Uganda, Tanzania, Rwanda, Burundi, South Sudan, DRC) are exempt. Confirm your country's requirements at etakenya.go.ke." },
      { type:"h2", text:"How to Apply" },
      { type:"p", text:"Go to etakenya.go.ke — the official government portal. Do not use third-party sites that charge higher fees. The single-entry eTA costs USD 30; multiple-entry costs USD 50." },
      { type:"p", text:"You'll need: a valid passport (6+ months remaining), a passport photo, proof of accommodation (hotel booking or invitation letter), onward flight details, and a credit/debit card for payment." },
      { type:"h2", text:"Processing Time" },
      { type:"p", text:"Most applications are processed within 72 hours. Apply at least 5 business days before travel to allow buffer time. Approval comes via email — print it or save it on your phone." },
      { type:"h2", text:"Common Issues" },
      { type:"p", text:"The most common rejection reason is mismatched names between the application and passport. Type your name exactly as it appears in your passport, including middle names. Rejection doesn't refund your fee — reapply carefully." },
      { type:"tip", text:"Diaspora Kenyans with foreign passports still need an eTA or can apply for a Kenya Citizen Certificate to enter on their second passport. Contact the Kenyan High Commission in your country for clarity." },
    ],
    relatedSlugs: ["first-safari","48-hours-diani","naivasha-itinerary"],
  },
  "nairobi-nyama-choma": {
    slug: "nairobi-nyama-choma",
    title: "Best Nyama Choma Joints in Nairobi",
    category: "Food",
    date: "February 10, 2026",
    readTime: "5 min read",
    excerpt: "Where to find the most authentic grilled meat experience",
    img: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1400&q=85",
    author: { name: "Rooted Kenya", avatar: "https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=100&q=80" },
    tags: ["Nairobi","Nyama Choma","Food","Local"],
    body: [
      { type:"intro", text:"Nyama choma — grilled meat — is Kenya's most social food. You don't eat it alone and you don't rush it. The best joints are rarely the most advertised ones. Here's where the locals actually go." },
      { type:"h2", text:"The Classics" },
      { type:"p", text:"Carnivore Restaurant in Langata is the tourist favourite but genuinely delivers. The rotating skewers of game meat and standard cuts, the all-you-can-eat format, and the lively atmosphere make it a Nairobi institution. Expect to pay KES 3,500pp for the full experience." },
      { type:"p", text:"Nyama Mama in Westlands does a modern take — cleaner setting, same quality meat, better cocktails. Good for groups who want nyama choma without the full Carnivore experience." },
      { type:"h2", text:"Local Spots Worth Knowing" },
      { type:"p", text:"The stretch of nyama choma joints along Ngong Road near Dagoretti Corner is where Nairobi residents go for the real thing. Open-air, smoky, loud, and the goat ribs are exceptional. Budget KES 500–800pp." },
      { type:"p", text:"Mathare Social Hall on Thursdays runs a community nyama choma evening that has become one of Nairobi's best-kept social secrets. Check their Instagram for dates." },
      { type:"h2", text:"What to Order" },
      { type:"p", text:"Goat ribs (mbuzimchoma) are the standard. Beef fillet (nyama ya ng'ombe) if you're at a proper place. Always order the kachumbari (tomato and onion salad) and ugali or chips on the side. Tusker is mandatory." },
      { type:"tip", text:"The quality indicator: check if they're slaughtering on-site or have a butcher on the property. The best spots control their meat supply from the start." },
    ],
    relatedSlugs: ["nairobi-brunch","48-hours-diani","naivasha-itinerary"],
  },
};

// ─── PACKAGES (full detail) ───────────────────────────────────────────────────
export const PACKAGE_DATA = {
  weekend: {
    slug: "weekend",
    title: "Weekend Getaways",
    tagline: "2D/1N and 3D/2N escapes across Kenya with clear itineraries and transparent pricing",
    heroImg: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1400&q=85",
    icon: "🧳",
    category: "Weekend Packages",
    duration: "1–2 Nights",
    bestFor: ["Couples","Friend groups","Families","Solo travelers"],
    overview: "Our weekend getaway packages are built for people who want a proper reset without spending weeks planning. Every package includes where to stay, what to do, where to eat, estimated costs, and optional booking links. We cover Naivasha, Nanyuki, Diani, and Maasai Mara short trips.",
    inclusions: ["Accommodation (Budget / Mid / Premium options)","Activity suggestions with costs","Transport recommendations","Restaurant recommendations","Estimated total cost per person"],
    exclusions: ["Flights (costed separately)","Personal spending","Travel insurance"],
    tiers: [
      { name:"Budget",  price:"KES 8,000–14,000",  perPerson:true, note:"Guesthouse or basic lodge, matatu or shared transport" },
      { name:"Mid",     price:"KES 18,000–32,000",  perPerson:true, note:"Boutique hotel, private car, curated activities" },
      { name:"Premium", price:"KES 45,000–90,000+", perPerson:true, note:"5-star lodge, private vehicle, full board" },
    ],
    destinations: ["Naivasha","Nanyuki","Diani","Maasai Mara (short)"],
    gallery: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80",
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600&q=80",
      "https://images.unsplash.com/photo-1540202403-b7abd6747a18?w=600&q=80",
    ],
  },
  beach: {
    slug: "beach",
    title: "Beach Escapes",
    tagline: "Diani and Watamu beach packages with curated stays, water activities, and restaurant guides",
    heroImg: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=85",
    icon: "🏖️",
    category: "Beach Packages",
    duration: "2–4 Nights",
    bestFor: ["Couples","Groups","Families","Beach lovers"],
    overview: "Kenya's coast is exceptional — and Diani and Watamu are the two best-value beach destinations in East Africa. Our beach packages bundle the best accommodation, water activities, and restaurant recommendations into one clear plan with tiered pricing.",
    inclusions: ["Beachfront accommodation options","Water activity bookings (snorkelling, kitesurfing, boat trips)","Restaurant recommendations","Return transport options (SGR + matatu, flight)","3-day and 4-day itinerary options"],
    exclusions: ["Flights (quoted separately)","Personal spending","Marine park entry fees (costed in itinerary)"],
    tiers: [
      { name:"Budget",  price:"KES 12,000–20,000",  perPerson:true, note:"Guesthouse near beach, local restaurants, matatu" },
      { name:"Mid",     price:"KES 25,000–45,000",  perPerson:true, note:"Mid-range beach resort, breakfast, 1 water activity" },
      { name:"Premium", price:"KES 65,000–150,000+", perPerson:true, note:"5-star beachfront resort, all inclusive" },
    ],
    destinations: ["Diani Beach","Watamu","Malindi","Mombasa Old Town"],
    gallery: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
      "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=600&q=80",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80",
    ],
  },
  safari: {
    slug: "safari",
    title: "Safari Packages",
    tagline: "Maasai Mara and Amboseli safari bundles — structured, priced clearly, and built for first-timers",
    heroImg: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1400&q=85",
    icon: "🦁",
    category: "Safari Packages",
    duration: "3–5 Days",
    bestFor: ["First-time safari-goers","Wildlife photographers","Couples","Small groups"],
    overview: "The Maasai Mara and Amboseli are Kenya's two great safari destinations. Our packages break down exactly what you get at each budget tier, who the best operators are, what the migration season means for pricing, and how to plan a safari that matches your expectations.",
    inclusions: ["Park entry fees","Game drives (AM and PM)","Accommodation (tented camp or lodge)","Full board (meals in camp)","Qualified safari guide","Airport/airstrip transfers"],
    exclusions: ["Domestic flights (Wilson Airport ↔ Mara/Amboseli)","Optional balloon safari (~KES 50,000pp)","Drinks","Travel insurance"],
    tiers: [
      { name:"Budget",  price:"KES 25,000–45,000",    perPerson:true, note:"Tented budget camp, shared vehicle, drive-in" },
      { name:"Mid",     price:"KES 60,000–100,000",   perPerson:true, note:"Mid-range lodge, private vehicle, fly-in" },
      { name:"Premium", price:"KES 160,000–400,000+", perPerson:true, note:"Luxury lodge, private guide, fly-in, all inclusive" },
    ],
    destinations: ["Maasai Mara","Amboseli","Tsavo","Samburu"],
    gallery: [
      "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600&q=80",
      "https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=600&q=80",
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80",
    ],
  },
  city: {
    slug: "city",
    title: "City Experiences",
    tagline: "Nairobi date nights, brunch crawls, and curated urban experiences with transport and restaurant bookings",
    heroImg: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1400&q=85",
    icon: "🏙️",
    category: "City Packages",
    duration: "Day / Evening",
    bestFor: ["Couples","Foodies","Date nights","Friend groups"],
    overview: "You don't have to leave Nairobi for a great experience. Our city packages bundle restaurant bookings, activity plans, and transport coordination into one seamless evening or full day. Brunch crawls, date nights, cultural tours — all planned so you just show up.",
    inclusions: ["Restaurant reservations","Activity bookings","Transport coordination","Curated itinerary with timing","Concierge support on the day"],
    exclusions: ["Food and drink costs","Ticket prices for events","Personal spending"],
    tiers: [
      { name:"Budget",  price:"KES 2,000–5,000",   perPerson:true, note:"Planning and booking only, you pay at venues" },
      { name:"Mid",     price:"KES 8,000–15,000",  perPerson:true, note:"Includes 1 prepaid experience + dinner booking" },
      { name:"Premium", price:"KES 20,000–50,000+",perPerson:true, note:"Full evening managed — transport, dinner, drinks, event" },
    ],
    destinations: ["Nairobi CBD","Westlands","Karen","Kilimani","Gigiri"],
    gallery: [
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80",
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80",
    ],
  },
  event: {
    slug: "event",
    title: "Event Bundles",
    tagline: "Concert + dinner, nightlife + transport — event-ready plans with all logistics sorted",
    heroImg: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1400&q=85",
    icon: "🎶",
    category: "Event Packages",
    duration: "Evening / Night",
    bestFor: ["Groups","Couples","Event-goers","Nightlife"],
    overview: "Concert tickets without a dinner plan, or a great restaurant with no idea what to do after — our event bundles solve both. We combine the best events in Nairobi with nearby restaurant bookings, transport, and optional VIP upgrades into one package.",
    inclusions: ["Event tickets (or booking guidance)","Dinner reservation at a nearby restaurant","Transport coordination (Uber/private car)","Timing plan for the evening","Optional VIP or table upgrades"],
    exclusions: ["Food and drink costs at dinner","Personal spending","Additional Uber costs"],
    tiers: [
      { name:"Budget",  price:"KES 3,000–7,000",   perPerson:true, note:"Event + dinner plan, self-arranged transport" },
      { name:"Mid",     price:"KES 10,000–18,000", perPerson:true, note:"Event tickets + dinner booking + transport coordination" },
      { name:"Premium", price:"KES 25,000–60,000+",perPerson:true, note:"VIP tickets + fine dining + private driver" },
    ],
    destinations: ["Nairobi — Westlands","Nairobi — Karen","Blankets & Wine venue","Carnivore Grounds"],
    gallery: [
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80",
      "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80",
      "https://images.unsplash.com/photo-1411679126435-10f7f2e48e69?w=600&q=80",
    ],
  },
};

// ─── RESTAURANTS (full detail) ────────────────────────────────────────────────
export const RESTAURANT_DATA = {
  "talisman-restaurant": {
    slug: "talisman-restaurant",
    name: "Talisman Restaurant",
    area: "Karen, Nairobi",
    cuisine: "Continental",
    budget: "Premium",
    priceRange: "KES 2,500 – 5,000 pp",
    img: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=85",
    description: "Talisman is a Nairobi institution — a garden restaurant in Karen that has been the city's favourite for special occasions for over two decades. The food is excellent, the setting is beautiful, and the service is professional without being stiff.",
    openingHours: "Tue–Sun: 12pm–10:30pm",
    bestFor: ["Date night","Celebrations","Sunday lunch","Business dinner"],
    mustOrder: ["Grilled fillet mignon","Talisman seafood platter","The cheese board"],
    bookingRequired: true,
    phone: "+254 722 363 887",
    location: "Karen, Nairobi (off Karen Road)",
    tags: ["Karen","Garden dining","Fine dining","Date night"],
    gallery: [
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80",
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80",
    ],
  },
  "carnivore-restaurant": {
    slug: "carnivore-restaurant",
    name: "Carnivore Restaurant",
    area: "Langata, Nairobi",
    cuisine: "Nyama Choma",
    budget: "Mid",
    priceRange: "KES 3,500 pp (all-you-can-eat)",
    img: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1200&q=85",
    description: "Carnivore is Nairobi's most famous restaurant and for good reason. Servers bring skewers of meat — beef, chicken, lamb, sausage, and game meats — continuously to your table until you surrender by lowering the small white flag. Loud, fun, and genuinely good.",
    openingHours: "Daily: 12pm–11pm",
    bestFor: ["Groups","Tourists","Meat lovers","Birthday dinners"],
    mustOrder: ["The full Carnivore experience — it's all-you-can-eat","Dessert board"],
    bookingRequired: false,
    phone: "+254 20 605 0775",
    location: "Langata Road, Langata, Nairobi",
    tags: ["Langata","Nyama choma","All-you-can-eat","Groups"],
    gallery: [
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80",
    ],
  },
  "ali-barbours-cave": {
    slug: "ali-barbours-cave",
    name: "Ali Barbour's Cave Restaurant",
    area: "Diani Beach",
    cuisine: "Seafood",
    budget: "Premium",
    priceRange: "KES 4,000 – 8,000 pp",
    img: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=1200&q=85",
    description: "Set in a natural coral cave lit by candles and fairy lights, Ali Barbour's is one of Kenya's most extraordinary dining experiences. The seafood is excellent and fresh. Make a reservation — this place fills up every weekend.",
    openingHours: "Daily: 6:30pm–10:30pm (dinner only)",
    bestFor: ["Date night","Honeymoons","Special occasions"],
    mustOrder: ["Fresh lobster","Garlic prawns","Catch of the day"],
    bookingRequired: true,
    phone: "+254 722 205 564",
    location: "Diani Beach Road, Diani",
    tags: ["Diani","Cave dining","Seafood","Romantic"],
    gallery: [
      "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=600&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80",
    ],
  },
};

// ─── EVENTS (full detail) ─────────────────────────────────────────────────────
export const EVENT_DATA = {
  "blankets-and-wine": {
    slug: "blankets-and-wine",
    title: "Blankets & Wine",
    category: "concerts",
    date: "April 19, 2026",
    time: "2pm – 9pm",
    venue: "Uhuru Gardens, Nairobi",
    area: "Nairobi",
    price: "KES 2,500 – 8,000",
    img: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&q=85",
    description: "Kenya's most beloved outdoor music festival. Bring a blanket, a bottle of wine, and your best people. Live music across three stages, excellent food vendors, and the kind of relaxed outdoor atmosphere that Nairobi does best.",
    lineup: ["Sauti Sol","Bien","Bensoul","Multiple DJs"],
    ticketLink: "https://www.ticketsasa.com",
    whatToPair: "Pre-dinner at Talisman (Karen) or post-event drinks at Havana Westlands",
    tips: ["Buy tickets 2 weeks ahead — sells out","Bring a proper blanket — the grass is damp","Uber surge is brutal at 9pm — share with others or book 30 mins early"],
    tags: ["Music","Outdoor","Festival","Nairobi"],
    gallery: [
      "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80",
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80",
    ],
  },
  "koroga-festival": {
    slug: "koroga-festival",
    title: "Koroga Festival",
    category: "cultural",
    date: "April 26, 2026",
    time: "12pm – 8pm",
    venue: "Private Grounds, Karen",
    area: "Karen, Nairobi",
    price: "KES 1,500 – 3,000",
    img: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&q=85",
    description: "Koroga is a monthly Sunday afternoon outdoor event — live music, great food vendors, beautiful grounds in Karen. It's relaxed, well-organised, and consistently delivers a quality afternoon. Bring the family or come with friends.",
    lineup: ["Rotating monthly acts","DJ sets","Spoken word"],
    ticketLink: "https://www.ticketsasa.com",
    whatToPair: "Pre-event brunch at About Thyme (nearby on Ngong Road)",
    tips: ["The Karen venue is worth the trip","Parking is well organised","Bring cash for food vendors","Great for families — spacious grounds"],
    tags: ["Cultural","Outdoor","Monthly","Families"],
    gallery: [
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80",
      "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80",
    ],
  },
};

export const BLOG_LIST = Object.values(BLOG_DATA);
export const PACKAGE_LIST = Object.values(PACKAGE_DATA);
export const RESTAURANT_LIST = Object.values(RESTAURANT_DATA);
export const EVENT_LIST = Object.values(EVENT_DATA);
